import streamlit as st
from utils.pdf_extractor import extract_text_from_pdf
from config.sample_data import SAMPLE_BLOOD_REPORT


def show_analysis_form(ai_service, auth_service, session_id: str):
    """
    Render the analysis form:
    - Report source selection (Upload PDF / Use Sample Report)
    - Patient details
    - "Analyze Report" button
    Returns (report_text, analysis_result) or (None, None) if not yet submitted.
    """
    st.markdown("### <span style='color:#4F46E5;'>●</span> Blood Report Analysis", unsafe_allow_html=True)

    tab_doc, tab_patient = st.tabs(["Document Upload", "Patient Context & Analysis"])
    
    report_text = None

    # ── Step 1: Report Source ────────────────────────────────────────────────
    with tab_doc:
        st.markdown("<br/>", unsafe_allow_html=True)
        source = st.radio(
            "Report Source",
            options=["Upload PDF", "Use Sample Report"],
            horizontal=True,
            label_visibility="collapsed",
        )

        if source == "Upload PDF":
            uploaded_file = st.file_uploader(
                "Upload your blood report PDF (max 20MB, 50 pages)",
                type=["pdf", "PDF"],
                help="Only PDF files containing blood test results are accepted.",
            )
            if uploaded_file:
                if uploaded_file.size > 20 * 1024 * 1024:
                    st.error("File size exceeds 20MB limit.")
                else:
                    with st.spinner("Extracting text from PDF..."):
                        extracted = extract_text_from_pdf(uploaded_file)
                    if len(extracted) < 50 or extracted.startswith("Error") or extracted.startswith("Could") or extracted.startswith("PDF") or extracted.startswith("This") or extracted.startswith("Uploaded"):
                        st.error(extracted)
                    else:
                        report_text = extracted
                        st.success(f"PDF extracted successfully ({len(report_text):,} characters). Please proceed to Step 2.")
        else:
            report_text = SAMPLE_BLOOD_REPORT
            st.info("Sample report loaded. You can view it below or proceed directly to Step 2.")
            with st.expander("Preview Sample Report"):
                st.text(report_text)

    # ── Step 2: Patient Details ──────────────────────────────────────────────
    with tab_patient:
        st.markdown("<br/>", unsafe_allow_html=True)
        col1, col2 = st.columns(2)
        with col1:
            age = st.number_input("Age", min_value=1, max_value=120, value=30, step=1)
        with col2:
            gender = st.selectbox("Gender", ["Male", "Female", "Other", "Prefer not to say"])
        medical_history = st.text_area(
            "Relevant Medical History (optional)",
            placeholder="e.g. Diabetes Type 2, Hypertension, recent surgery...",
            height=80,
        )

        st.markdown("<br/>", unsafe_allow_html=True)
        remaining = ai_service.get_remaining_analyses()
        if remaining <= 0:
            st.warning("You have reached today's analysis limit. Please try again tomorrow.")
            return None, None

        analyze_clicked = st.button(
            f"Analyze Report ({remaining} left today)",
            type="primary",
            use_container_width=True,
            disabled=report_text is None,
        )

    if analyze_clicked:
        if not report_text:
            st.error("Please provide a blood report first.")
            return None, None

        chat_history = st.session_state.get("chat_history", [])
        patient_data = {
            "age": age,
            "gender": gender,
            "medical_history": medical_history or "None",
        }

        with st.spinner("🤖 Analyzing your blood report... This may take a moment."):
            result = ai_service.analyze_report(report_text, patient_data, chat_history)

        if result["success"]:
            model_used = result.get("model_used", "")
            st.caption(f"Analysis generated by: `{model_used}`")

            # Persist to Supabase
            auth_service.update_session_data(
                session_id,
                report_text=report_text,
                analysis_result=result["content"],
            )
            return report_text, result["content"]
        else:
            st.error(f"Analysis failed: {result.get('error', 'Unknown error')}")
            return None, None

    return None, None
